### ISSUE TITLE
Error while cloning the following repo

### ISSUE THREAD

**Issue by jjj1986** [arredondo23/hybrid_assembly_slurm#1]
We are getting error while cloning the following repo

git clone https://gitlab.com/mmb-umcu/hybrid_assembly.git

remote: The project you are looking for could not be found.

**Comment by arredondo23** [comment]
Hi @jjj1986, 

Sorry for this typo, the documentation was not correctly migrated from gitlab to my personal github account. You should run instead:
`git clone https://github.com/arredondo23/hybrid_assembly_slurm.git` 

I will modify now the documentation, thanks for raising the issue! Let me know if you encounter any other issues 

Sergio
